test_that("`cd_stack()` plots as expected", {
  library(baguette)
  library(dials)
  library(dplyr)
  library(hardhat)
  library(kernlab)
  library(kknn)
  library(parsnip)
  library(ranger)
  library(recipes)
  library(rsample)
  library(rules)
  library(stacks)
  library(stats)
  library(tidyselect)
  library(tune)
  library(workflows)
  library(workflowsets)
  library(yardstick)
  library(viruslearner)
  data("obj_mod1", package = "viruslearner")
  expect_snapshot(
    print(
      class(obj_mod1)
    )
  )
})